- key: c minor
{(6__)(__)8_r}c''babcbagab
agfgad-cbcd-
g,fe+fg(6ag)(ab)c(cde+)
{(6__)(__)8_r}fe+fgabagab
e,d-cd-efedef
b,agabagfga
gfefgagfga
{(6__)}a+gf+ga+b+6cd(ed)(cd)8b+r
6r(d-cb!)(ag)(fe+)8fr(6ag)(fa)
8gc,4c'~6c(g-'fe)(d-c)(ba+)
8br(6d-c)(bd-)8cf,4f'~
6(fb) \sR:0.3 (ag-){(6__)} \sR:0.3 fe \sR:0.3 d-c \sR:0.3 d-ed-cbagf
\knee \sR:0.5 \sHL:3 (6e+a')(gf) {(6__)}e+d-cbagfg6agfe
\sR:0.5 \sHL:3 (6de')(dc)(b+a)(gf)4g\fermata 8re+'
fd-cb4a6r(agf)
[8e+f]fe+2f\fermata 