8rf\"_Evangelist:_" ba+bcdf,
4r8c'-6aa8gfrb
8.g6g4g 6rg+bc8db
8f-'f-rb,d6g+,g+8f-'e
c-c-ra4dr||\key:C \clef:bass  \break
8e-\"_Jesus:_" e-rcb-ara
dg,gb4d,d
8r6fg8a-fc'6cb4d
re,8c'6ag+4b
re,f+g
f+e
2r
R
=lyrics
Und ging ein we-nig für-bass, 
fiel auf die Er-de, und be-te-te, 
daß so es mög-lich wä-re, 
die Stun-de vor-ü-ber-gin-ge, und sprach:

Ab-ba, mein Va-ter, es ist dir al-les mög-lich, 
ü-ber-he-be mich die-ses Kelchs.
Doch nicht wie ich will, son-dern wie du willst.