4d+<7>r2r
4a'<4+2>g+<6>2r
2e+,<6>r
r4f'r
e<6+>r2d~ ||
1d
2f,g
bc~
1c4<><42><6><7>
4rdg,r
g+<7>ra+<7>r \key:f+
b+<6+>r2r
4c<7#>rb+<7>r
c-<6>c<5`>d+<7!>r
a+<7>r2r
4be<6!>ra,<6!>
d<6>rg,<6+>r
rf'<#>b,g<#>
g-<6>e+<65`>b'<4+2>a+<6>
f+a<4+2>g+<#>g-<6>
f<#>e+<8!5`#>rf<#> || \time:2/2 \key:B
2b4rb'
4.b8b2a
1g2<><5`>
2g,a-
1a!<65`>
b<h>
b+<65> || \time:4/4 \key:b
8c'<#>rb<4+2>ra+<6>rb<h>r
e,<65>re+<7>rf<#>rb,<h>r