4g' defg
abg\fermata [8bc]
4dd[8bc]4d
2c4b\fermata b
cba8[ga]
4bbg\fermata [8bc]
4dd[8bc]4d
2c4b\fermata b
cba8[ga]
4bbg\fermata a
bbe,f
8[gf]4ed\fermata d
gab8[ab]
4cb2a
2.g\fermata
=lyrics
Bet-rüb-tes Herz, sei wohl-ge-mut,
tu nicht so-gar ver-za-gen.
Es wird noch wer-den al-les gut,
all dein Kreuz, Not und Kla-gen
wird sich in lau-ter Fröh-lich-keit
ver-wan-deln in gar kur-zer Zeit,
das wirst du wohl er-fah---ren.
