 4a' gfgg
agg\fermata a
g+aaa
(ag+)e :|. g
gg[8de]4f
eee\fermata e
[8de]4fed
ef+d\fermata e
[8de][f+e]4e[8ag]
(4f![8ed])4c+\fermata
=lyrics
Was Men-schen-kraft und -witz an-fässt, 
Soll uns bil-lig nicht schre-cken,

Wenn sie aufs klüg-ste grei-fen an, 
So geht doch Gott ein and-re Bahn, 
Es steht in sei-nen Hän-den.

=lyrics(2)
Er si-tzet an der höch-sten Stätt,
Er wird ihr'n Rat auf-de-cken.
