4a ef[8ed]4c
fgc,\fermata a
e'2f8ed
2e4a,:|.g'
[8c,d][ef]4gg+
a[8c,d]4e\fermata [8ag]
[fe]4d[8ef+]4g
c,dg,\fermata [8e'f+]
4g[8f+g+][ag][fe]
(4de)a,\fermata
=lyrics
Was Men-schen-kraft und -witz an-fässt, 
Soll uns bil-lig nicht schre-cken,

Wenn sie aufs klüg-ste grei-fen an, 
So geht doch Gott ein and-re Bahn, 
Es steht in sei-nen Hän-den.

=lyrics(2)
Er si-tzet an der höch-sten Stätt,
Er wird ihr'n Rat auf-de-cken.
