4c'' [8cb] [ab] [cd] 4e
ddc\fermata c
b [8ab] 4cd
2b4a :|. \partBreak d
ee[8bc]4d
ccb\fermata c
d[8ab]4cb
aag\fermata c
b[8ab]4c[8dc]
2b4a\fermata
=lyrics
Was Men-schen-kraft und -witz an-fässt, 
Soll uns bil-lig nicht schre-cken,

Wenn sie aufs klüg-ste grei-fen an, 
So geht doch Gott ein and-re Bahn, 
Es steht in sei-nen Hän-den.

=lyrics(2)
Er si-tzet an der höch-sten Stätt,
Er wird ihr'n Rat auf-de-cken.
