4e' [8ed][cd][eb]4c
cbe\fermata e
[8ed][cb]4af'
(4.e8d)4c:|.b
c[8ga]4bb
bag+\fermata a
ad[8g,a][bd]
[cb]4ab\fermata [8ga]
[bc+]4d[8cb]4a
(4.a8g+)4e\fermata
=lyrics
Was Men-schen-kraft und -witz an-fässt, 
Soll uns bil-lig nicht schre-cken,

Wenn sie aufs klüg-ste grei-fen an, 
So geht doch Gott ein and-re Bahn, 
Es steht in sei-nen Hän-den.

=lyrics(2)
Er si-tzet an der höch-sten Stätt,
Er wird ihr'n Rat auf-de-cken.
