8r6a\"_Evangelist:_" a8c6cb8ccr6ab
4c8cac6cc8c6ba
4bb8ra8.c6c
4c8cb4c8ra
8.c6c8cc4c8ba
4bbr8ra
c6cc8bcd6dd8dc
4ar2r|| \key:f+
4r8c6cc8.c6c8cb
4c8c6cb8ccbc
d6dd4dr8f,f
4.b8b4ba
(gf)2r
R
=lyrics
Und er kauf-te ein Lein-wand, 
und nahm Ihn ab, und wi-ckel-te Ihn 
in die Lein-wand, und leg-te Ihn in ein Grab, 
das war in ei-nen Fel-sen ge-hau-en; 
und wäl-ze-te ei-nen Stein vor des Gra-bes Tür. 
A-ber Ma-ri-a Mag-da-le-na und Ma-ri-a 
Jo-ses schau-e-ten zu, 
wo er hin-ge-le-get ward.__