4c' [6cd8e-][e-d][ec][fe]
(4a[8gf])4e\fermata e
[8ed][dc][c6de]4f
([8f6ed]4e)c\fermata  :|. f
fffe
[8dc]~[cb+]4g\fermata e-'
[8de!][f6ga]4gf
(4.a8g)[8gf+\fermata]4g
gf4.g[6fe]
4f2f4e
2.c\fermata
=lyrics
O Lamm Got-tes, un-schul-dig
am Stamm des Kreuz's ge-schlach-tet, 

all Sünd hast du ge-tra-gen,
sonst müss-ten wir ver-za-gen.
Er-barm dich un-ser, o Je--su.

=lyrics(2)
all-zeit er-fund'n ge-dul-dig,
wie-wohl du warst ver-ach-tet,
