 8[f,g] 4abb[8ag]
(4fg)c\fermata a
de[8fe][db]
2c4f,\fermata :|. f'
[8fe][dc]4b+c+
([8de][fg])4c,!\fermata a
bf'[8fe]4f~
[8ff+][gg,]4d'\fermata [8bb+]
4cdef
8[a,6bc8dc]4(bc)
2.f,\fermata
=lyrics
O Lamm Got-tes, un-schul-dig
am Stamm des Kreuz's ge-schlach-tet, 

all Sünd hast du ge-tra-gen,
sonst müss-ten wir ver-za-gen.
Er-barm dich un-ser, o_ Je-su.

=lyrics(2)
all-zeit er-fund'n ge-dul-dig,
wie-wohl du warst ver-ach-tet,
