.|: 4f' ffc'c
2d4c\fermata \break c
f,gab
(a8[gf])4f\fermata :|. \break a
aaga
([8fe]4d)c\fermata \break c'
dcc[8ab]
(4cb)a\fermata \break d
[8cb]4aga
(ca)2g
2.f\fermata
=lyrics
O Lamm Got-tes, un-schul-dig
am Stamm des Kreuz's ge-schlach-tet, 

all Sünd hast du ge-tra-gen,
sonst müss-ten wir ver-za-gen.
Er-barm dich un-ser, o_ Je-su.

=lyrics(2)
all-zeit er-fund'n ge-dul-dig,
wie-wohl du warst ver-ach-tet,
