8[ab] 4.c[6ba]4gc
(cb+)g\fermata a
ag4.f8d'
(4.c8b)4a\fermata :|. c
cdda
([8ag][a6gf])4e\fermata f
[8fg][ab]4.c8d
(4e-d)d\fermata 8[df]
4.e8d[dc]4c
[8cafa](4d[8cb])
2.a\fermata
=lyrics
O Lamm Got-tes, un-schul-dig
am Stamm des Kreuz's ge-schlach-tet, 

all Sünd hast du ge-tra-gen,
sonst müss-ten wir ver-za-gen.
Er-barm dich un-ser, o_ Je--su.

=lyrics(2)
all-zeit er-fund'n ge-dul-dig,
wie-wohl du warst ver-ach-tet,
