- key: b- major
- time: 4/4
4f'\"_col Soprano_"
bcde
4.f8e4d\fermata g
fede
2c\trill 4b\fermata  :| f' 
ggc,\fermata c \partBreak 
ffb,\fermata d
cbab
2g\trill 4f\fermata f'
edcd
2c\trill 4b\fermata 
=lyrics
Was Gott thut, das ist wohl-ge-than,
da-bei will ich ver-blei-ben,

so wird Gott mich ganz vä-ter-lich
in sei-nen Ar-men hal-ten:
drum lass' ich ihn nur wal-ten.
=lyrics(2)
Es mag mich auf die rau-he Bahn
Noth, Tod und E-lend trei-ben,