R*21 || \key:F
8rf'\"_Testis I:_" f6ff4g8gg
8g6gg4a8a6aa8.b6a
8grrc4.c8c
4c8caaaaa
2r8r6c+c+8d6da
8b+grd'dd4r
r8cc4a8gc~
cc4.a8baa
4a8g+grf+rb
r6gg8f+6f+b+8ac4r
r4b+b+b+
b+8aa4ag+ || \key:C
R*4
=lyrics
Wir ha-ben ge-hö-ret, 
  Wir ha-ben ge-hö-ret, daß er sa-ge-te: 
Ich will den Tem-pel, Ich will den Tem-pel
der mit Hän-den ge-macht ist, 
ab-bre-chen, und in drei-en Ta-gen 
ei-nen an-dern bau-en, 
der nicht, nicht,
  nicht mit Hän-den ge-macht ist,
  der nicht mit Hän-den ge-macht ist.
