1(f'g) 4ffff4ff2e1f\fermata |
1(fg) 4eeeee 4dd2d1(c+d)\fermata || \break

1(fg) 4fff4ff2e1f\fermata |
1(fg) 4eeeeee 4dd2d1(c+d)\fermata || \break

1(fg) 4ffff4ff2(e1f)\fermata |
1(fg) 4eeeeeee 4dd2d1(c+d)\fermata
 
=lyrics
Gott_ sei uns gnä-dig und barm-her-zig, 
Und_ geb uns sei-nen gött-li-chen Se-gen._

Er_ laß uns sein Ant-litz leuch-ten, 
Daß_ wir auf Er-den erken-nen sei-ne We-ge._

Es_ seg-ne uns Gott, un-ser Gott,_
Es_ seg-ne uns Gott, und geb' uns 
  sei-nen Frie-den._