1f'g 2fff4ff2e1f\fermata |
1fg 2eee 4dd2d1c+d\fermata || \break

1fg 2ff4ff2e1f\fermata |
1fg 2eeee 4dd2d1c+d\fermata || \break

1fg 2ff4ff2e1f\fermata |
1fg 2eeeeee 4dd2dd1c+d\fermata

=lyrics
Gott sei uns gnä-dig und barm-her-zig, 
Und geb uns sei-nen gött-li-chen Se-gen.

Er laß uns sein Ant-litz leuch-ten, 
Daß wir auf Er-den erken-nen sei-ne We-ge.

Es seg-ne uns Gott, un-ser Gott, 
Es seg-ne uns Gott, und geb' uns 
  sei-nen Frie-den, A-men.