1(fc) 4ffff4b,f2c'1f,\fermata |
1(f'c) 4ccccc 4gg2d'1(ad)\fermata || \break

1(fc) 4fff4b,f2c'1f,\fermata |
1(f'c) 4cccccc 4gg2d'1(ad)\fermata || \break

1(fc) 4ffff4b,f2(c'1f,)\fermata |
1(f'c) 4ccccccc 4gg2d'1(ad)\fermata

=lyrics
Gott_ sei uns gnä-dig und barm-her-zig, 
Und_ geb uns sei-nen gött-li-chen Se-gen._

Er_ laß uns sein Ant-litz leuch-ten, 
Daß_ wir auf Er-den erken-nen sei-ne We-ge._

Es_ seg-ne uns Gott, un-ser Gott,_
Es_ seg-ne uns Gott, und geb' uns 
  sei-nen Frie-den._