1fc 2fff4b,f2c'1f,\fermata |
1f'c 2ccc 4gg2d'1ad\fermata || \break

1fc 2ff4b,f2c'1f,\fermata |
1f'c 2cccc 4gg2d'1ad\fermata || \break

1fc 2ff4b,f2c'1f,\fermata |
1f'c 2cccccc 4gg2d'd1ad\fermata

=lyrics
Gott sei uns gnä-dig und barm-her-zig, 
Und geb uns sei-nen gött-li-chen Se-gen.

Er laß uns sein Ant-litz leuch-ten, 
Daß wir auf Er-den erken-nen sei-ne We-ge.

Es seg-ne uns Gott, un-ser Gott, 
Es seg-ne uns Gott, und geb' uns 
  sei-nen Frie-den, A-men.