1a'c 2aaa4ba2g1f\fermata |
1ac 2ggg 4gd2f1ed\fermata || \break

1a'c 2aa4ba2g1f\fermata |
1ac 2gggg 4gd2f1ed\fermata || \break

1a'c 2aa4ba2g1f\fermata |
1ac 2gggggg 4gd2ff1ed\fermata

=lyrics
Gott sei uns gnä-dig und barm-her-zig, 
Und geb uns sei-nen gött-li-chen Se-gen.

Er laß uns sein Ant-litz leuch-ten, 
Daß wir auf Er-den erken-nen sei-ne We-ge.

Es seg-ne uns Gott, un-ser Gott, 
Es seg-ne uns Gott, und geb' uns 
  sei-nen Frie-den, A-men.