1(a'c) 4aaaa4ba2g1f\fermata |
1(ac) 4ggggg 4gd2f1(ed)\fermata || \break

1(a'c) 4aaa4ba2g1f\fermata |
1(ac) 4gggggg 4gd2f1(ed)\fermata || \break

1(a'c) 4aaaa4ba2(g1f)\fermata |
1(ac) 4ggggggg 4gd2f(1ed)\fermata 

=lyrics
Gott_ sei uns gnä-dig und barm-her-zig, 
Und_ geb uns sei-nen gött-li-chen Se-gen._

Er_ laß uns sein Ant-litz leuch-ten, 
Daß_ wir auf Er-den erken-nen sei-ne We-ge._

Es_ seg-ne uns Gott, un-ser Gott,_
Es_ seg-ne uns Gott, und geb' uns 
  sei-nen Frie-den._