1c'e 2ccc4dc2c1a\fermata |
1ce 2ccc 4bb2a1af+\fermata || \break

1c'e 2cc4dc2c1a\fermata |
1ce 2cccc 4bb2a1af+\fermata || \break

1c'e 2cc4dc2c1a\fermata |
1ce 2cccccc 4bb2aa1af+\fermata

=lyrics
Gott sei uns gnä-dig und barm-her-zig, 
Und geb uns sei-nen gött-li-chen Se-gen.

Er laß uns sein Ant-litz leuch-ten, 
Daß wir auf Er-den erken-nen sei-ne We-ge.

Es seg-ne uns Gott, un-ser Gott, 
Es seg-ne uns Gott, und geb' uns 
  sei-nen Frie-den, A-men.