1(c'e) 4cccc4dc2c1a\fermata |
1(ce) 4ccccc 4bb2a1(af+)\fermata || \break

1(c'e) 4ccc4dc2c1a\fermata |
1(ce) 4cccccc 4bb2a1(af+)\fermata || \break

1(c'e) 4cccc4dc2(c1a)\fermata |
1(ce) 4ccccccc 4bb2a1(af+)\fermata

=lyrics
Gott_ sei uns gnä-dig und barm-her-zig, 
Und_ geb uns sei-nen gött-li-chen Se-gen._

Er_ laß uns sein Ant-litz leuch-ten, 
Daß_ wir auf Er-den erken-nen sei-ne We-ge._

Es_ seg-ne uns Gott, un-ser Gott,_
Es_ seg-ne uns Gott, und geb' uns 
  sei-nen Frie-den._