4f' g[8fe+][fg]4a
(ag)e\fermata e
e[8ed]4cf
2.e+\fermata :|. 4f
e![8ed+][ef]4g
2a4g\fermata b
ab4.b8a
2.g\fermata 4g
eaag-
2f4f\fermata f
fffe+
2.c\fermata
=lyrics
Kei-nen hat Gott ver-las-sen,
Der Ihm ver-traut all-zeit, 

Gott will die Sei-nen schü-tzen, 
Zu-letzt er-he-ben hoch, 
Und ge-ben was ihm nü-tzet,
Hier zeit-lich und auch dort.
=lyrics(2)
Ob ihn'n gleich schon viel has-sen, 
Ge-schieht ihm doch kein Leid. 
