4f e+c[8fe]4d
2e4a,\fermata a'
[8gf]4e[8fe]4d
2.c\fermata :|. 4d+
e[8ef]4ge
[8a,bcd+]4e\fermata g
a[8ga]4bb,
2.e\fermata 4e
[8ab][ag-][fg-][fe]
[dcde]4f\fermata a,
d[8cb]4cc
2.f\fermata
=lyrics
Kei-nen hat Gott ver-las-sen,
Der Ihm ver-traut all-zeit, 

Gott will die Sei-nen schü-tzen, 
Zu-letzt er-he-ben hoch, 
Und ge-ben was ihm nü-tzet,
Hier zeit-lich und auch dort.
=lyrics(2)
Ob ihn'n gleich schon viel has-sen, 
Ge-schieht ihm doch kein Leid. 
