 4c'' cccf
(4.e8d)4c\fermata [8cd]
4eg,ab2.c\fermata :|. 4b
bbbb
2c4b\fermata b
[8cd]4eed+
2.e\fermata 4e
ccde
2f4c\fermata c
b[8ag]4.g8f
2.f\fermata
=lyrics
Kei-nen hat Gott ver-las-sen,
Der Ihm ver-traut all-zeit, 

Gott will die Sei-nen schü-tzen, 
Zu-letzt er-he-ben hoch, 
Und ge-ben was ihm nü-tzet,
Hier zeit-lich und auch dort.
=lyrics(2)
Ob ihn gleich schon viel has-sen, 
Ge-schieht ihm doch kein Leid. 
