4a [8ga]4ba[8dc]
([ba]4b)4a\fermata a
bb[8ag]4f
2.g\fermata :|. 4f
[8gf][ga]4be
2e4e\fermata e
e[8ef]4gf
2.e\fermata 4b
ae'fc
cba\fermata c
f,d'[8ca]4b
2.a+\fermata
=lyrics
Kei-nen hat Gott ver-las-sen,
Der Ihm ver-traut all-zeit, 

Gott will die Sei-nen schü-tzen, 
Zu-letzt er-he-ben hoch, 
Und ge-ben was ihm nü-tzet,
Hier zeit-lich und auch dort.
=lyrics(2)
Ob ihn gleich schon viel has-sen, 
Ge-schieht ihm doch kein Leid. 
