 [8d'c] 4b[8ag][fg][fe]
4dea,\fermata b
[8cd]4ef[8ga]
[bgaa,]4d\fermata :|. [8de]
4fg+[8ad,]4e
2a,\fermata 4bf'
ged\fermata f
b,c(de)
4a,\fermata [8e'f]4gd
4d+eb\fermata b
[8ef][ge][ca][dc]
([8bg]4a)d\fermata
=lyrics
Das Wort sie sol-len las-sen stahn,
Und kein'n Dank da-zu ha-ben.

Neh-men sie uns den Leib,
Gut, Ehr, Kind und Weib,
Laß fah-ren da-hin,
Sie ha-ben kein Ge-winn,
Das Reich Gott's muss uns blei-ben.
=lyrics(2)
Er ist bei uns wohl auf dem Plan
Mit sei-nem Geist und Ga-ben.
