4d'' dd[8ab]4c
[8dc]4ba\fermata d
cba[8ba]
([gf]4e)d\fermata :|. d
a'bag+
2a\fermata 4d,a'
bcd\fermata c
dc2b
4a\fermata bba
[8ba]4gf\fermata d'
cba[8ba]
([gf]4e)d\fermata
=lyrics
Das Wort sie sol-len las-sen stahn,
Und kein'n Dank da-zu ha-ben.

Neh-men sie uns den Leib,
Gut, Ehr, Kind und Weib,
Laß fah-ren da-hin,
Sie ha-ben kein Ge-winn,
Das Reich Gott's muss uns blei-ben.
=lyrics(2)
Er ist bei uns wohl auf dem Plan
Mit sei-nem Geist und Ga-ben.
