 R*3


2.r4r || \time:3/4 \partial:4 4r
4rra
e'dr
cad
dc8ef
2.g~
g~
4g[8fg]4a~
agr
R
4rr8a,b
2.c-~
4c-br
efg
4.f8e4e
4aaa
4.a8a4a
bar || \time:4/4 \key:G
R*2
 || \key:C
R*16














 ||
R*10








 ||
R*5



  \key:b
R*3

 || \time:3/4
\instr:"Alto I" 4r b,d
R*3


4e+g+r
R || \time:4/4
\instr:"Alto II" R
4r e+g+r
=lyrics
Wo willst du,
daß wir hin-ge-hen,
und be-rei---ten, und be-rei-ten,
daß du das Os-ter-lamm,
daß du das Os-ter-lamm es-sest?

Bin ich's? Bin ich's? Bin ich's?