R*3


2.r4r || \time:3/4 \partial:4 4a,
dca'
gfr
cdg,
aar
R*2

4rr8f'f
[gfgabg]
[edefge]
4ffr
rr8b,a
4ggr
a'aa
4.a8a4a
4a,aa
4.a8a4a
g+ar || \time:4/4 \key:G
R*2
 || \key:C
R*16














 ||
R*10








 ||
R*5



 || \key:b
R*3

 || \time:3/4
\instr R
4rrg'
brr
R
4rbd
R || \time:4/4
R*2

=lyrics
Wo willst du, Wo willst du,
daß wir hin-ge-hen,
und be-rei---ten, und be-rei-ten,
daß du das Os-ter-lamm,
daß du das Os-ter-lamm es-sest?

Bin ich's? Bin ich's?