R*10









2re'
ga
bb
ag
1f~
4fr2r
R*3


2rb
cd
ed
1c
b
R*10









2re,
ga
bb
ag
1f~
4fr2r
R*3


2rb
cd
ed
1c
b~
8br4r2r
R*4



2rb
ed
cb
ag
1f
R*6





2rb
ag
fa
gf
1e~
e
R*2
=lyrics
Mach's mit mir, Gott, nach dei-ner Güt,_
Hilf mir in mei-nen Lei-den!_
Was ich dich bitt', ver-sag mich nicht,_
Wenn sich mein Seel soll schei-den._
So nimm sie, Herr, in dei-ne Händ,_
Ist al-les gut, wenn gut das End._