- score:
//  - page_break: before
  - layout:
    - ragged_last: false
- parts:
  - alto1:
    - render_modes: part
    - notation_size: tiny
    - staff_size: -2
  - violoncello:
    - include_parts: alto1
  - continuo:
    - include_parts: alto1
  - fagotto:
    - include_parts: alto1
//  - violino1:
//    - include_parts: alto1
//  - violino2:
//    - include_parts: alto1
//  - viola1:
//    - include_parts: alto1
//  - viola2:
//    - include_parts: alto1
  
