8{c4}f'd
{c2}eeef
fgef
dbf'd
geea
fbbb
e,eee
fec'b
{v}bgafgefdegfagbab
caga8g\trill (6fe)8ecbb
{c2}bf'dd
efdd
eegf
fdeg
ffgf
ffcf
8f6de8feddee
{c2}ccbb'
8bbba+{c2}bb
bbbf
gfff
ecff
ffb,b
bbcb
g'fff
ffeg
ggef
fb,ec
dfgb
bfbf
4er2r
r4r{c2}f
ddee
effg
efdb
f'dge
eafb
bbe,e
eefe
c'b{v}bgafgefd
egfagbabcaga8g(6fe)
8ecbb4b\fermata r
R*2

2r{c2}f+'a+
f+a+gg
gggg
8ead,g4gr
R*2

2r{c2}dd
ddcc
dge+e
a+gf+g
ed4dr \dacapo