\key:g R*10 |:*2
2*3/2rc'
cb+
cd
ed
cr
R*8
2*3/2rc
dd
gf
1*3/2e
2*3/2dr|*
R*4 |*
R *|
R*3
2*3/2rg
fe
df
ed
cr
R*3
2*3/2re
dc
bg
bc
dr
R*4
2*3/2rc
ef
(2.*3/2g4*3/2f
2*3/2e)f
d~[8dfe]4*3/2d\trill
1*3/2c
R*5  || \insertTimeSignature:4/4
=lyrics
Und weil ich denn in mei-nem Sinn,
wie ich zu-vor ge-kla-get,

und woll-te gern im Blu-te dein
von Sün-den ab-ge-wa-schen sein,

wie Da-vid und_ Ma-nas--se.
=lyrics(2)
auch ein be-trüb-ter Sün-der bin,
den sein Ge-wis-sen na-get,
