4d' dd[8de][ed]
(4dc)4d\fermata e
[8de]4f4.f8e
2.d\fermata :|. 4f
[8eg][fe]4dg
(g[8fe])4f\fermata f
gffe
2.d+\fermata 4e
ee[8fg+]4a
(ag+)a\fermata [8d,c]
[bc]4d[8db]4c
2.d\fermata
=lyrics
Be-fiehl du dei-ne We-ge,
Und was dein Her-ze kränkt,

Der Wol-ken, Luft und Win-den
Giebt We-ge, Lauf und Bahn,
Der wird auch We-ge fin-den,
Da dein Fuß ge-hen kann.

=lyrics(2)
Der al-ler-treu-sten Pfle-ge
Des, der den him-mel lenkt,