4d gf[8b,c]4d
(g,a)d\fermata c
[8bc][de]4ff,
2.b\fermata :|. 4b
ef[8gf]4e
2d4d\fermata d
[8gf][ed+][ef][ga]
2.b\fermata 4g+
ag+fe
(d+e)a,\fermata d
e[8fg]4aa,
2.d\fermata
=lyrics
Be-fiehl du dei-ne We-ge,
Und was dein Her-ze kränkt,

Der Wol-ken, Luft und Win-den
Giebt We-ge, Lauf und Bahn,
Der wird auch We-ge fin-den,
Da dein Fuß ge-hen kann.

=lyrics(2)
Der al-ler-treu-sten Pfle-ge
Des, der den him-mel lenkt,