4a ga[8ba]4a
(ba)a\fermata a+
bbba+ \break
2.b\fermata :|. [8ba]
[gb][dc][ba][ga]
(4b[8ag])4a\fermata d
dc-bb
2.b\fermata 4b
ab[8ab][ca]
(4f'e)e\fermata a,
gaaa
2.a\fermata 
=lyrics
Be-fiehl du dei-ne We-ge,
Und was dein Her-ze kränkt,

Der Wol-ken, Luft und Win-den
Giebt We-ge, Lauf und Bahn,
Der wird auch We-ge fin-den,
Da dein Fuß ge-hen kann.

=lyrics(2)
Der al-ler-treu-sten Pfle-ge
Des, der den him-mel lenkt,