4e'd[(8dc)][(cb)]
4ba2e'
[(8ea)][(ag)][(gf)]4e
(ed)2b
4ef8[ef][ge]
4dc2b+
4cdee
[8e6de8fd]2e
4eee+f
[(8d-c)][(cd)]2e+
4c[8cd]4e![8d-e]
2ff
4f[8ef]4gg
[8ef][b,c]2d
4.e8b[(ef)][(gc,)]
([d6ec]4d)2b
=lyrics
Je-su, oh-ne Mis-se-tat,
im Gar-ten Vor-han-den,
da man dich ge-bun-den hat
fest mit har-ten Ban-den.
wenn uns will der ar-ge Feind
mit der Sün-de bin-den,
so laß uns, oh Men-schen-freund!
Da-durch Lö-sung fin-den.