ebcd
ef2g
4abc8[(ba)]
4(bb,)2e
([8ed])([dc])2c~
8cb+ce2g
8[c,c'][ba][gf][ed]
[cfdb]2e
4c8([ba])(g4g')8f
([fe+])4f2c
[8fg]4a4gg-
(8fe4f)2b,
8[db]4e8[ec]4g'
8[gf][ga]2b
4.e,8d[cc']8[ba]
4(bb,)2e
=lyrics
Je-su, oh-ne Mis-se-tat,
im Gar-ten Vor-han-den,
da man dich ge-bun-den hat
fest mit har-ten Ban-den.
wenn uns will der ar-ge Feind
mit der Sün-de bin-den,
so laß uns, oh Men-schen-freund!
Da-durch Lö-sung fin-den.