4b[(8ba)]4gf
[(8ee')][(ed-)]2@
4cd!([8ed])[(ec)]
(4.b8a)2g
4bb[8cd][ec]
[ag]4g2g
4gbbb
8[cafb]2b
4ccbc
ba2g
[8ab][cb]4.b8c
(4d-c)2d
4bbe[8db]
[cd]4e2b
[8ba][gf][ed]4e
(4.b'8a)2g
=lyrics
Je-su, oh-ne Mis-se-tat,
im Gar-ten Vor-han-den,
da man dich ge-bun-den hat
fest mit har-ten Ban-den.
wenn uns will der ar-ge Feind
mit der Sün-de bin-den,
so laß uns, oh Men-schen-freund!
Da-durch Lö-sung fin-den.