4bbee
fedc\fermata
bbed
gg2f\fermata :|.
4eeed-
[8cd]4e+ff\fermata
[8ef]4gag
ffgg\fermata
eeed
e[8bc]2d\fermata
4efee
ed2b\fermata
=lyrics
Man hat dich sehr hart ver-höh-net
Dich mit gros-sem Schimpf be-legt

Daß du möch-test mich er-göt-zen,
Mir die Eh-ren-kron auf-set-zen?
Tau-send, tau-send-mal sei dir,
Lieb-ster Je-su, Dank da-für!

=lyrics(2)
Und mit Dor-nen gar gek-rö-net:
Was hat dich dar-zu be-wegt,
