4ede[8ag]
4fcb+c\fermata
d-deg
e+f2b,\fermata :|.
4g'ea,b
ccff\fermata
gea[8cb]
4a+be,e\fermata
gea,b
[8cd]4e2b\fermata
4edcb
a+b2e\fermata
=lyrics
Man hat dich sehr hart ver-höh-net
Dich mit gros-sem Schimpf be-legt

Daß du möch-test mich er-göt-zen,
Mir die Eh-ren-kron auf-set-zen.
Tau-send, tau-send-mal sei dir,
Lieb-ster Je-su, Dank da-für!

=lyrics(2)
Und mit Dor-nen gar gek-rö-net:
Was hat dich dar-zu be-wegt?
