 4e'fge
agfe\fermata
ffgb
ba+2b\fermata :|.
4bgcb
agaa\fermata
bbce
edee\fermata
bgcb
ag2f\fermata
4gbag
ff2e\fermata
=lyrics
Man hat dich sehr hart ver-höh-net
Dich mit gros-sem Schimpf be-legt

Daß du möch-test mich er-göt-zen,
Mir die Eh-ren-kron auf-set-zen.
Tau-send, tau-send-mal sei dir,
Lieb-ster Je-su, Dank da-für!

=lyrics(2)
Und mit Dor-nen gar gek-rö-net:
Was hat dich dar-zu be-wegt?
