4gfbc
ccgg\fermata
ffbb
d-c2d\fermata :|.
4bb[8ag]4f
fc'cc\fermata
beee
cbbb\fermata
bb[8ag]4f
[8ef][ga+]2b\fermata
4bbcc
c[8ba]2g\fermata
=lyrics
Man hat dich sehr hart ver-höh-net
Dich mit gros-sem Schimpf be-legt

Daß du möch-test mich er-göt-zen,
Mir die Eh-ren-kron auf-set-zen.
Tau-send, tau-send-mal sei dir,
Lieb-ster Je-su, Dank da-für!

=lyrics(2)
Und mit Dor-nen gar gek-rö-net:
Was hat dich dar-zu be-wegt?
