  8[f'g] 4agaa
b8[ag]4f\fermata g+
agfb
ba+f\fermata :|. a
aa8[ef]4g
fg+a+\fermata b
8[ba]4g+f8[ea]
4ag+e\fermata g+
a8[g+a+]4b8[e,f]
4g8[fe]4d+\fermata

=lyrics
Sie stel-len uns wie Ket-zern nach,
Nach un-sern Blut sie Trach--ten,
=lyrics(2)
Noch rüh-men sie sich Chris-ten auch,
Die Gott al-lein groß ach--ten.
=lyrics
Ach Gott! der theu-re Na-me dein,
Muß ih-rer Schalk-heit Dec-kel seyn,
Du wirst ein-mahl auf-wa--chen.
