- key: b minor
- pickup: 4
  4b'
fg8[fe]4d
gad,\fermata b
ae'8[b'a][gf]
4e+fb\fermata :|. a
8[d,e][fg]4aa+
be+,f\fermata 8[ba]
[g+f]4e8[fg+]4a
d+,ea,\fermata b
8[cd]4e8[b'a][gf]
4efb,\fermata

=lyrics
Sie stel-len uns wie Ket-zern nach,
Nach un-sern Blut sie Trach--ten,
=lyrics(2)
Noch rüh-men sie sich Chris-ten auch,
Die Gott al-lein groß ach--ten.
=lyrics
Ach Gott! der theu-re Na-me dein,
Muß ih-rer Schalk-heit Dec-kel seyn,
Du wirst ein-mahl auf-wa--chen.
