- key: b minor
- pickup: 4
  4d''
d8[bc][de]4f
eed\fermata d
c8[bc]4d8[ed]
2c4b\fermata :|. e
ff8[cd]4e
ddc\fermata d
e8[bc]4dc
bba\fermata d
c8[bc]4d8[ed]
2c4b\fermata

=lyrics
Sie stel-len uns wie Ket-zern nach,
Nach un-sern Blut sie Trach-ten,
=lyrics(2)
Noch rüh-men sie sich Chris-ten auch,
Die Gott al-lein groß ach-ten.
=lyrics
Ach Gott! der theu-re Na-me dein,
Muß ih-rer Schalk-heit Dec-kel seyn,
Du wirst ein-mahl auf-wa-chen.
