  4d' | dd8[dc]4d
dcd\fermata d
ee8[dc]4b
8[cd]4ed\fermata :|. c
d8[ab]4cc
8[dc]4bf'\fermata f
b,e8[a,b]4c
f8[ed]4c\fermata d
ee8[dc]4b
ba+f\fermata

=lyrics
Sie stel-len uns wie Ket-zern nach,
Nach un-sern Blut sie Trach--ten,
=lyrics(2)
Noch rüh-men sie sich Chris-ten auch,
Die Gott al-lein groß ach--ten.
=lyrics
Ach Gott! der theu-re Na-me dein,
Muß ih-rer Schalk-heit Dec-kel seyn,
Du wirst ein-mahl auf-wa--chen.
