4c' fefa
[8ba]4ga\fermata c,
fggf
[8fe]4fe\fermata e
ed[8de]4f
(fe)c\fermata :| f
ggf+g
gf+d\fermata f
f[8c'b][ag]4f
fec\fermata

=lyrics
Wach auf, oh Mensch, vom Sün-den-Schlaf 
er-mun-tre dich, ver-lor'-nes Schaf,
und bes-sre bald dein Le-ben!

Viel-leicht ist heut der letz-te Tag,
wer weiß-noch, wie man ster-ben mag.

=lyrics(2)
Wach auf, es ist doch ho-he Zeit,
es kommt her-an die E-wig-keit,
dir dei-nen Lohn zu ge-ben.
