4f fgaf
bcf,\fermata [8fe]
4d[8cb]4ad
g,[8ab]4c\fermata c+
8[de][fd]4g[8dc]
(4bc)f,\fermata :|. f'
ee-dc+
ddg,\fermata a
bc[8de]4f
ccf,\fermata

=lyrics
Wach auf, oh Mensch, vom Sün-den-Schlaf 
er-mun-tre dich, ver-lohr-nes Schaaf,
und bes-sre bald dein Le-ben!

Viel-leicht ist heut der letz-te Tag,
wer weiß-noch, wie man ster-ben mag.

=lyrics(2)
Wach auf, es ist doch ho-he Zeit,
es kommt her-an die E-wig-keit,
dir dei-nen Lohn zu ge-ben.
