[8f'g] 4abcc
def\fermata [8f,g]
4abcc
bag\fermata a
ffba
2g4f\fermata :| c'
gabbaag\fermata c
defa,
ggf\fermata

=lyrics
Wach auf, oh Mensch, vom Sün-den-Schlaf 
er-mun-tre dich, ver-lor'-nes Schaf,
und bes-sre bald dein Le-ben!

Viel-leicht ist heut der letz-te Tag,
wer weiß-noch, wie man ster-ben mag.

=lyrics(2)
Wach auf, es ist doch ho-he Zeit,
es kommt her-an die E-wig-keit,
dir dei-nen Lohn zu ge-ben.
