[8ab] 4cb[8ac]4f
fcc\fermata a
dd[8cb]4a
bcc\fermata a
aaga
(d[8cb])4a\fermata :|. a
bcde
[8a,b]4cb\fermata c
[8ba]4g[8fg][ab]
[cg][cb]4a\fermata


=lyrics
Wach auf, oh Mensch, vom Sün-den-Schlaf 
er-mun-tre dich, ver-lor'-nes Schaf,
und bes-sre bald dein Le-ben!

Viel-leicht ist heut der letz-te Tag,
wer weiß-noch, wie man ster-ben mag.

=lyrics(2)
Wach auf, es ist doch ho-he Zeit,
es kommt her-an die E-wig-keit,
dir dei-nen Lohn zu ge-ben.
