- key: e- major
- time: 4/4
R*4
4r8rb,efga
2b~4.b8c
f,([6ga])([ba])([gf])4e4.!a
[6ba]4.g[6a+b][cba+g]
8a+frf,bcde
fb,4.b'8cf,a+
bb4r2r
R*2
4r \slur:_(,0.3)(,0.6)_ ([8f6ag])2g~
1g~
4gr8rgca+
[8.f+6g]([8.g\trill 3f+g])4a+8rd,
([6b'a+])([cg])8.f+6g8gg,rg'
4f+8rg4.e[6dc]
2.c~8c([6ba+])
([8g'6f+\trill])g8b,a+gg4r
R*3
2r4r8rd'
([ed])4d4r8rg
([ag])4g([8a6bc])4e,
d8rb'e+,fa([6gf])
8ffrf([gf])4f
4r8rb,([cb])4b
4.a'8b4g8rf
gfga2b~
[8b6cb][agfe]4.a[6ba]
[8g6fg][agfe]8fb,re,
abcdefga
be,4be,r
R*3
R\fermataMarkup
=lyrics
Ich fol-ge Chri-sto nach,_
von ihm will ich nicht las-------sen,
ich fol-ge Chri-sto nach, 
von ihm will ich nicht las-sen

im Wohl,_ im Wohl und Un-ge-mach,
im Le-ben und Er-blas-sen,
im Wohl und Un-ge-mach,_
im Le-ben und Er-blas-sen.

Ich küs-se, ich küs-se Chri-sti Schmach,
ich will sein Kreuz um-fas-sen, 
ich küs-se, ich küs-se Chri-sti Schmach,
ich will sein Kreuz um-fas-------sen.

Ich fol-ge Chri-sto nach, 
von ihm will ich nicht las-sen.