4e' 8[ed]4dd8[cb]
2a4be
eff8[ed]
(4c#4.d8c) :|. [a'g]
4fe8[ec]4f
(4.g8f)4ec
c8[cbß]4aa
2a4re'
ed8[ef#][gg#]
(4aa,)e'8[ec#]
[ab]4c!d8[dc]
4b~[8b6(ba4b)]\fermata
=lyrics
Ich will hier bei dir ste-hen,
ver-ach-te mich doch nicht,_

wenn dein Haupt wird er-blas-sen 
im letz-ten To-des-stoß,
als-denn will ich dich fas-sen
in mei-nen Arm und Schoß._
=lyrics(2)
von dir will ich nicht ge-hen, 
wenn mir mein Her-ze bricht,_ 
