8[gb] [ac]4b8[cg]4g
([8afdd'])([db])4g#
4.a8c[dd,][gf]
(4e[8.f6g]4a) :|. e'
d8[dc]4cd
(g,8[ab])4cc
f,ge8[fg]
2a4ra
bb8[ba][e'd]
([cc#]4d)g,8[ag]
[fg]4aab
([8bg#ec']4b)\fermata \finedellaparteprima
=lyrics
Ich will hier bei dir ste-hen,
ver-ach-te mich doch nicht,_

wenn dein Haupt wird er-blas-sen 
im letz-ten To-des-stoß,
als-denn will ich dich fas-sen
in mei-nen Arm und Schoß._
=lyrics(2)
von dir will ich nicht ge-hen, 
wenn mir mein Her-ze bricht,_
