- key: b- major
- time: 4/4
4d'
fffb
baf\fermata [8ed]
4cg'fg
2f4f\fermata  :| b
b[8cb]4aa \partBreak 
4.b8a-4gf
e+dcd
2c4c\fermata b
[8bc][de]4ff
2f4d\fermata 
=lyrics
Was Gott thut, das ist wohl-ge-than,
da-bei will ich ver-blei-ben,

so wird Gott mich ganz vä-ter-lich
in sei-nen Ar-men hal-ten:
drum lass' ich ihn nur wal-ten.
=lyrics(2)
Es mag mich auf die rau-he Bahn
Noth, Tod und E-lend trei-ben,