- key: b- major
- time: 4/4
4b,
b'abg
dfb,\fermata e
f[8ga]4be,
2f4b,\fermata  :| b'
e,e+f\fermata e
dde\fermata b
c[8de+]4fb,
2c4f,\fermata d'
[8ga]4b[8fe][db]
2f4b\fermata 
=lyrics
Was Gott thut, das ist wohl-ge-than,
da-bei will ich ver-blei-ben,

so wird Gott mich ganz vä-ter-lich
in sei-nen Ar-men hal-ten:
drum lass' ich ihn nur wal-ten.
=lyrics(2)
Es mag mich auf die rau-he Bahn
Noth, Tod und E-lend trei-ben,