- key: b- major
- time: 4/4
4b
dcb[8bc]
4dcb\fermata b
a[8bc]4d[8cb]
(4ba)4b\fermata  :| d
[8ed]4c4ff
[8fe][dc]4b[8ba]
4gf[8fa][gf]
(4fe+)f\fermata f
g[8fg]4ab
(4ba)4f\fermata 
=lyrics
Was Gott thut, das ist wohl-ge-than,
da-bei will ich ver-blei-ben,

so wird Gott mich ganz vä-ter-lich
in sei-nen Ar-men hal-ten:
drum lass' ich ihn nur wal-ten.
=lyrics(2)
Es mag mich auf die rau-he Bahn
Noth, Tod und E-lend trei-ben,