 4erd<6>r
d-<643>rc<7h>r
2r4f<b>b,<6b>
rcfr
e<643>rd<7#>r
R
2r4f<4!2>e<6>
rd<#>g,r
e+'<5`>ff+<6>g<h>
g+<6>a<#>g<4+2>r
f+<6>re<#>r
2r4ra,<#> || \key:C
d,r2r
2r4f+<6>r
R*2

2r4d'<#>g,
e<#>r2r
4g+'<6>rg<4+2>r
2r4f<6>r
re<#>a,<#>r
R
2r4dr
R*3


2r4g,<b>r || \key:d
8b.g.e-'.d.c.a.d.c.
b.g.e-'dcadc
bge'!dc+af'e
db+edc!adc
bge-'dcae-'d
bga'gfda'g
e-ca'gb,ge'd
c+af'edba'g
eca'gdbe-d
c+af'ec+ab'a
c+,af'edbf'e
dba'ga,fc'b
ag+baag+ba
ag+baag+ba
4a8aa2a