 4erdr
d-rcr
2r4fb,
rcfr
erdr
R
2r4fe
rdg,r
e+'ff+g
g+agr
f+rer
2r4ra, || \key:C
d,r2r
2r4f+r
R*2

2r4d'g,
er2r
4g+'rgr
2r4fr
rea,r
R
2r4dr
R*3


2r4g,r || \key:d
8b.\"_(Turba)_"  g.e-'.d.c.a.d.c.
b.g.e-'dcadc
bge'!dc+af'e
db+edc!adc
bge-'dcae-'d
bga'gfda'g
e-ca'gb,ge'd
c+af'edba'g
eca'gdbe-d
c+af'ec+ab'a
c+,af'edbf'e
dba'ga,fc'b
ag+baag+ba
ag+baag+ba
4a8aa2a || \key:C
4g+r2r
4ar2r
4dg,rf' ||
8e-\"_(Turba)_" ca-'ge-cb-'a
e!d+feed+fe
e,d+feed+fe
ed+feed+fe
4e8ee2e