 R*27 || \key:d \instr
8<d'g,>\staccatissimo r4r8<a'e->\staccatissimo r4r
8<d,g,>\staccatissimo r4r8<a'e->\staccatissimo r4r
8<d,g,>r4r 8<a'e>r4r
8<ad,>r4r 8<ae>r4r
8<d,g,>r4r 8<a'd,>r4r
8<d,g,>r4r 8<a'd,>r4r
8<g,c,>r4r 8<d'g,>r4r
8<a'e>r4r 8<d,a>r4r
8<ac,>r4r 8<cd,>r4r
8<eg,>r4r 8<a,c+,>r4r
8<ac+,>r4r 8<d'e,>r4r
8<g,g,>r4r 8<ac,>r4r
8<eb>r4r 8<da>r4r
8<fa,>r4r 8<da>r4r
4<c+e,>8<c+e,><c+e,>2<c+e,>
