4r8g\"_Evangelist:_" gc6cc8c6de
8ebrcba4r
8r6aa8c+deere
g,6gg8ab-rb-ag
c+6c+ddaaa8db4g+
8r6aa8d+6c+b8.e6e8er
c+6ba8.d6d8dab6bb
8ca8.d+6e8eb4r
R
=lyrics
Und die Jün-ger ver-lie-ßen Ihn al-le, und flo-hen.
Und es war ein Jüng-ling, der fol-ge-te Ihm nach,
der war mit Lein-wand bek-lei-det auf der blo-ßen Haut 
und die Jüng-lin-ge grif-fen ihn. 
Er a-ber ließ den Lein-wand fah-ren und flo-he bloß von ih-nen.