 4d' dcdd
(cd)c\fermata f
be+,ff
(fgf\fermata) :|. [8fg+]
4aaeg
(ab-)a\fermata d,
dddc
(a[8bc]4d)\fermata e
eaaa
(fe)e\fermata d
e-ddc
(edc\fermata)
=lyrics
Du ed-les An-ge-sich-te,
Vor dem sonst schrickt und scheut_

Wie bist du so er-blei-chet,
Wer hat dein Au-gen-licht,_
Dem sonst kein Licht mehr glei-chet, 
So schreck-lich zu-ge-richt?_
=lyrics(2)
Das gro-ße Welt-ge-rich-te,
Wie bist du so ver-speit?_
