4d g,a[8bc]4d
(ag)f\fermata f'
e+cff
(geb)\fermata :|. b'
afga
(b-g)d\fermata f
gfea,
(dcb)\fermata g+'
ag!fe
(d+e)a,\fermata d
cdaa
(a+bf)\fermata
=lyrics
Du ed-les An-ge-sich-te,
Vor dem sonst schrickt und scheut_

Wie bist du so er-blei-chet,
Wer hat dein Au-gen-licht,_
Dem sonst kein Licht mehr glei-chet, 
So schreck-lich zu-ge-richt?_
=lyrics(2)
Das gro-ße Welt-ge-rich-te,
Wie bist du so ver-speit?_
