4a [8gf]4eda'
(ab)a+\fermata @
bbba+
(d+ed+)\fermata :|. 4d
edbe
(fg)f\fermata a,
gaba
2.f\fermata 4b
acde
(a,g+)a\fermata a
b-aae
(c'ba+)\fermata
=lyrics
Du ed-les An-ge-sich-te,
Vor dem sonst schrickt und scheut_

Wie bist du so er-blei-chet,
Wer hat dein Au-gen-licht,
Dem sonst kein Licht mehr glei-chet, 
So schreck-lich zu-ge-richt?_
=lyrics(2)
Das gro-ße Welt-ge-rich-te,
Wie bist du so ver-speit?_
