- key: g minor
- time: 4/4
\mark:#4 4re'e8ee
4er2r
4rb'b8aa
4br2r
4ra-a-8gf || \tempo:Largo \rmark
4g(6cb)(ba-)4a-r
{8r_4_}fgc,f
b+,ccf
gecd
bca-g
gcfc
fgef
d-ccf
gefd
eca-'d,
c'gfd
e+cd-c
cfb,e
a-,d-e+c
dedg,
e'a-d,b
cfdc
f+dda
8rg'4.a8d,6rb'gb
{(6__)8_6r___}cbcafababgeg
agafdfgf+ge+ce+
{4_8r_}dge+f
da'd,g
ac,g'g
ad,4g8r \ficta e+
{4_8r_}dfb+,f'
b+,e+c+d
gc,dd
egaa
bbad,
ccag'
c,dgg
4f+6rbdb{(6__)8_6r___}gfgaca
fefgbg8ecdf+
4d \breathe rr8gg
4ggc,a'
1g\fermata  || \insertTimeSignature:12/8
