- key: g minor
- time: 4/4
\mark:#4 4rbb8bb
4br2r
4ree8ff
4fr2r
4rff8ff || \tempo:Largo \rmark
8e+[cde+]4fr
{4_8r_}rb,a-a-
ggfa-
cecd
bca-b+
ge+'cc
bba-a-
bgfa-
gg'ff
eedd
cefg
e+fb,c
ccg'g,
cf,gc
g'ea-d,
g,cdb
ca-d,g
d'dad
g,c4.d8g,
{6r___8__}e'gefcdfdeb
cecaf6rbgb4a
{8r_4_}abca
dcf+,g
8r e+'4a,{8r_4_}dg,
e+'a,g'e+!
fa,b+a
dg,e+'d
bcab
becd
bgf'd
cgf+'b,
ea,dg,
ag{6r___(6__)8_}e'gecbc
dfdbab{6r___8__}acaaa
4b \breathe rr8g'g
4ggga
1d,\fermata  || \insertTimeSignature:12/8
