- empty_staves: hide
- key: g
- instrument_names: hide
- score:
  - page_break: none
// - movement_source: Freddy Eichelberger
- parts:
  - violoncello:
    - include_parts: tenore1
  - theorbe:
    - include_parts: tenore1
  - gamba1:
    - include_parts: tenore1,continuo
  - violino1:
    - include_parts: tenore1
  - violino2:
    - include_parts: tenore1
  - viola:
    - include_parts: tenore1
  