4r8a'fc'6cd8e-[6e-d]
4d8b-cdara
4b8b6bc4db
8rgcb-ag4r
r6rgga8b6rc8d6db
6g+g+g+a8b6bc8d6de8fe
8dc+6rc+c+d ec+8a+rc+
df+,ba[g+f+]4r
r8f+6ab8.c+6c+8c+d
e6ec+8a+6bc+8dd4r
- end_barline: |
=lyrics
Und da er in Be-tha-nien war, in Si-mo-nis,
des Aus-sät-zi-gen Hau-se, und saß zu Ti-sche,
da kam ein Weib, die hat-te ein Glas mit
un-ge-fälsch-tem und köst-li-chem Nar-den-Was-ser,
und sie zer-brach das Glas, und goss es auf sein Haupt.
Da wa-ren et-li-che, die wur-den un-wil-lig, und spra-chen:
